# Generated by Django 4.2.5 on 2024-01-10 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('304d46ed-e2e5-409d-8720-fca2e957688a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('304d46ed-e2e5-409d-8720-fca2e957688a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productmetainformation',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('304d46ed-e2e5-409d-8720-fca2e957688a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
